### ISSUE TITLE
GTM snippet body remove <noscript> tag

### ISSUE THREAD

**Issue by pmMelius** [tagconcierge/tc-prestashop-module-free#1]
After try to save plugin configuration, there is removed <noscript> tag from GTM snippet body. 
Module works, but Google Tag Assistant Legacy displays warnings.

**Comment by mfrankiewicz** [comment]
hello @pmMelius, thank you for reporting, i'll fix this today ;)

**Comment by mfrankiewicz** [comment]
@pmMelius fixed in https://github.com/tagconcierge/tc-prestashop-module-free/pull/2, thank you again for reporting
